# Generated by Django 3.1.3 on 2020-11-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceUsd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_page', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Pagina')),
                ('price_sell', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Precio Dolar',
                'verbose_name_plural': 'Precio Dolares',
            },
        ),
    ]
